# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: base_model.h5
  BASE_LOG_DIR: base_model_dir
  PREDICTION_OUTPUT_FILE: docs
  VISUALIZATION_PATH: images

data:
  RAW_DIR: data\raw
  PROCESSED_DIR: data\processed
  TRAIN_FILE: train.csv
  TEST_FILE: test.csv

params:
